---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bin
  namespace: argocd
spec:
  destination:
    namespace: bin-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: bin
    repoURL: https://helm.savew.dev/
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
