---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
spec:
  destination:
    namespace: gatus-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gatus
    helm:
      values: |
        config:
          ui:
            header: 'savew.dev - Health Status'
            title: 'Health Status | savew.dev'
            logo: "https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png"
            buttons:
              - name: "Source Code"
                link: https://github.com/saveside/k0s
          endpoints:
            - name: 'savew.dev'
              url: 'https://savew.dev'
              group: 'core'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'notes.savew.dev'
              url: 'https://notes.savew.dev/'
              group: 'core'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'ArgoCD'
              url: 'https://argo.savew.dev'
              group: 'essentials'
              interval: 300s
              conditions:
               - '[STATUS] == any(200, 201, 202)'
            - name: 'NextCloud'
              url: 'https://cloud.savew.dev/'
              group: 'tools'
              interval: 300s
              conditions:
              - '[STATUS] == any(200, 201, 202)'
            - name: 'Open WebUI'
              url: 'https://chat.savew.dev'
              group: 'tools'
              interval: 300s
              conditions:
              - '[STATUS] == any(200, 201, 202)'
            - name: 'Pastebin'
              url: 'https://paste.savew.dev'
              group: 'tools'
              interval: 300s
              conditions:
              - '[STATUS] == any(200, 201, 202)'
            - name: 'Umami'
              url: 'https://umami.savew.dev'
              group: 'tools'
              interval: 300s
              conditions:
              - '[STATUS] == any(200, 201, 202)'
            - name: 'Vaultwarden'
              url: 'https://vault.savew.dev'
              group: 'tools'
              interval: 300s
              conditions:
              - '[STATUS] == any(200, 201, 202)'
    repoURL: https://twin.github.io/helm-charts
    targetRevision: 1.*
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
