resources:
  - namespace.yml
  - configmap.yml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: 1.17.1
    namespace: traefik
    valuesInline:
      installCRDs: true

secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: traefik
    envs:
      - ./.env
