---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vaultwarden
    helm:
      parameters:
      - name: global.postgresql.secret.autoCreate
        value: kustomize
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
