---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-savew.dev
  namespace: traefik
spec:
  secretName: wildcard-savew.dev-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "adguard-home-k8s,radicale-k8s,maddy-k8s"
  dnsNames:
    - 'savew.dev'
    - '*.savew.dev'
  issuerRef:
    name: mainissuer
    kind: ClusterIssuer
