---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 33.*
    chart: traefik
    helm:
      parameters:
        - name: deployment.replicas
          value: "1"
        - name: ports.websecure.hostPort
          value: "443"
        - name: ingressClass.enabled
          value: "true"
        - name: ingressClass.isDefaultClass
          value: "true"
        - name: tlsStore.default.defaultCertificate.secretName
          value: wildcard-savew.dev-tls
      values: |
        additionalArguments:
          - --entrypoints.name.http3
          - --providers.kubernetescrd.allowCrossNamespace=true
          - --providers.kubernetescrd.allowExternalNameServices=true
          - --serverstransport.insecureskipverify=true
          #- --entryPoints.web.forwardedHeaders.insecure
          #- --log.level=DEBUG
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
