resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: nextcloud-app-secret
    namespace: nextcloud-k8s
    envs:
      - ./.app-secret.env
  - name: nextcloud-db-secret
    namespace: nextcloud-k8s
    envs:
      - ./.db-secret.env