---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anki-sync
  namespace: argocd
spec:
  destination:
    namespace: anki-sync-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anki-sync
    helm:
      values: |-
        global:
          main:
            accounts:
              - key: SYNC_USER1
                secret:
                  enabled: true
                  autoCreate: kustomize
                  name: user1-secret
                  key: credentials
    repoURL: https://helm.savew.dev/
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
